name: LiteLoaderLibs
main: index.js # JS入口文件，应该导出一个main函数（如main.js）
version: "0.0.1"
api: [ "1.0.13" ] # API版本，PNX从1.0.13起开始支持JS插件
load: STARTUP # 插件加载顺序，只能填写 STARTUP 或 POSTWORLD
# STARTUP: 此时服务器刚启动，地图尚未加载，通常用于依赖库
# POSTWORLD: 此时服务器所有地图都加载完毕，通常填写POSTWORLD即可
authors: # 此项可以不存在
  - Mcayear
  - CoolLoong
description: LiteLoader 的实现库
website: https://mc.xz.cn/list/Minecraft
softdepend: # 插件的软依赖项
  - LlamaEconomy
  - EconomyAPI
features:
  - WsClient
  - testFeature
